version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  db_test:
    image: postgres
    container_name: postgres_test_db
    restart: always
    ports:
      - "8080:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:database"
      - "db_test:database_test"
volumes:
  local_pgdata:
  pgadmin-data: